### PR TITLE
Add Air Five processing code

### LINKED ISSUE #10: Create Air Five processing code
- Extract
    - [x] schema
- Enrich
    - [x] logic
    - [x] schema
    - [x] tests
    - [x] documentation
- Validate
    - [x] logic
    - [x] tests
    - [x] documentation

### LINKED ISSUE #26: Abstract validation functions at package level
[DRY!](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

Writing indicator-specific validation functions is leading to a lot of repetition, as only thing that really changes is the scheme used for validation. Repetition is anti-pattern (and probably counter-revolutionary), so I think I should abstract these functions at the package level instead.

Should be implemented in conjunction with #27.

Related to #28.

### PR DESCRIPTION
**Pull request by EFT-Defra**
This pull request will close #10 and #26.

### CODE REVIEW

**Review by Jtsmith275 — COMMENTED** [review]
same add bounds routine here as in air four

**Review by Jtsmith275 — COMMENTED** [review]
looks good ready to approve

**Comment by EFT-Defra** [comment]
> same add bounds routine here as in air four

I agree, it needs to be abstracted.

**Comment by danlewis85** [comment]
In air 5, the bounds function assigns an upper and lower bound to the dataframe with generic names - Lower_CI_bound; Upper_CI_bound.

Will it be obvious in the metadata/elsewhere that these are 95% confidence intervals? Is it important to reflect the fact that these are 95% intervals in the column header?

**Comment by danlewis85** [comment]
I'm a little confused by `_kwargs_from_dict` - but that's because I don't really understand what it is doing. It's a nested try..except..else, so is it the case that you only want to return dictionary_indicator, and only in the event that the themes and indicators are valid (i.e. not key errors)?

**Comment by danlewis85** [comment]
Otherwise ready to approve.

**Review by danlewis85 — APPROVED** [review]

**Comment by danlewis85** [comment]
> In air 5, the bounds function assigns an upper and lower bound to the dataframe with generic names - Lower_CI_bound; Upper_CI_bound.
> 
> Will it be obvious in the metadata/elsewhere that these are 95% confidence intervals? Is it important to reflect the fact that these are 95% intervals in the column header?

Also, units of measurement might be worthwhile considering too?

**Comment by EFT-Defra** [comment]
> In air 5, the bounds function assigns an upper and lower bound to the dataframe with generic names - Lower_CI_bound; Upper_CI_bound.
> 
> Will it be obvious in the metadata/elsewhere that these are 95% confidence intervals? Is it important to reflect the fact that these are 95% intervals in the column header?

@danlewis85, I was just blindly replicating the column names in Excel workbook. I've just had another look and they do explain what these bounds represent in the associated commentary, so I think it's okay.

**Comment by EFT-Defra** [comment]
> I'm a little confused by `_kwargs_from_dict` - but that's because I don't really understand what it is doing. It's a nested try..except..else, so is it the case that you only want to return dictionary_indicator, and only in the event that the themes and indicators are valid (i.e. not key errors)?



> I'm a little confused by `_kwargs_from_dict` - but that's because I don't really understand what it is doing. It's a nested try..except..else, so is it the case that you only want to return dictionary_indicator, and only in the event that the themes and indicators are valid (i.e. not key errors)?

@danlewis85, so, for each theme/indicator DataFrame, I'm storing the kwargs needed for a pandas.read_excel() call in a JSON object. The idea here is that path, rows to skip, etc, can be edited there more easily than in the underlying code. `_kwargs_from_dict` receives a dictionary from `_dict_from_json_file` in the format:

```
{"theme": {
    "indicator": {
        "kw": "arg",
        ...,
    },
    ...,
}
```
So, yes, it looks up the theme and indicator in the dictionary and, if the exist, it returns the kwagrs dictionary but, if the don't it returns a KeyError. I'm not sure why I added these `try-expect-else` guardrails as it's very unlikely that the JSON object won't include the information needed but it seemed like a good idea at the time...

Does that explain what it's doing?

**Pull request merged**
